/*
 * Copyright (c) 2025.
 * Author Peter Placzek (tada5hi)
 * For the full copyright and license information,
 * view the LICENSE file that was distributed with this source code.
 */

export const SwaggerErrorCode = {
    SPEC_NOT_BUILT: 'SWAGGER_SPEC_NOT_BUILT',
    ENUM_UNSUPPORTED_TYPE: 'SWAGGER_ENUM_UNSUPPORTED_TYPE',
    BODY_PARAMETER_DUPLICATE: 'SWAGGER_BODY_PARAMETER_DUPLICATE',
    BODY_FORM_CONFLICT: 'SWAGGER_BODY_FORM_CONFLICT',
    BODY_PROP_TYPE_CONFLICT: 'SWAGGER_BODY_PROP_TYPE_CONFLICT',
    PARAMETER_SOURCE_UNSUPPORTED: 'SWAGGER_PARAMETER_SOURCE_UNSUPPORTED',
    METADATA_INVALID: 'SWAGGER_METADATA_INVALID',
} as const;
